'use strict';

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  Object.keys(value).forEach((key) => deepFreeze(value[key]));
  return value;
}

module.exports = deepFreeze({
  skills: [
    ['herb', '采药', 'standalone', true, null],
    ['mining', '采矿', 'standalone', true, null],
    ['woodcutting', '伐木', 'standalone', true, null],
    ['fishing', '钓鱼', 'standalone', true, null],
    ['alchemy', '炼丹', 'standalone', true, null],
    ['forging', '炼器', 'standalone', true, null],
    ['cooking', '烹饪', 'standalone', true, null],
    ['talisman', '符箓', 'standalone', true, null],
    ['charm', '魅力', 'relationship', false, 'social'],
    ['beastTaming', '御兽', 'homestead', true, null],
    ['farming', '种植', 'homestead', true, null],
    ['formation', '阵法', 'homestead', true, null]
  ],

  items: [
    ['copperOre', '铜矿石', 'material', 1, true],
    ['tinOre', '锡矿石', 'material', 1, true],
    ['ironOre', '铁矿石', 'material', 1, true],
    ['silverOre', '银矿石', 'material', 1, true],
    ['goldOre', '金矿石', 'material', 1, true],
    ['mithrilOre', '秘银矿', 'material', 1, true],
    ['adamantOre', '精金矿', 'material', 1, true],
    ['jadeShard', '灵玉矿', 'material', 1, true],
    ['darkIronOre', '玄铁矿', 'material', 1, true],
    ['crystalOre', '玄晶矿', 'material', 1, true],
    ['topaz', '黄玉', 'material', 1, true],
    ['sapphire', '蓝宝', 'material', 1, true],
    ['ruby', '红宝', 'material', 1, true],
    ['emerald', '翠玉', 'material', 1, true],
    ['diamond', '金钻', 'material', 1, true],
    ['darkCrystal', '暗晶', 'material', 1, true],
    ['willowWood', '杨柳木', 'material', 1, true],
    ['pineWood', '松木', 'material', 1, true],
    ['peachWood', '桃木', 'material', 1, true],
    ['nanmuWood', '楠木', 'material', 1, true],
    ['phoenixWood', '梧桐木', 'material', 1, true],
    ['spiritWood', '灵木', 'material', 1, true],
    ['thunderWood', '雷击木', 'material', 1, true],
    ['bloodSandalwood', '血檀', 'material', 1, true],
    ['ancientWood', '古木', 'material', 1, true],
    ['millenniumVine', '千年藤', 'material', 1, true],
    ['resin', '树脂', 'material', 1, true],
    ['birdNest', '鸟巢', 'material', 1, true],
    ['spiritPeach', '灵桃', 'material', 1, true],
    ['spiritFruit', '灵果', 'material', 1, true],
    ['spiritEgg', '灵禽蛋', 'material', 1, true],
    ['spiritWormSilk', '灵虫丝', 'material', 1, true],
    ['beastHide', '兽皮', 'material', 1, true],
    ['thunderHerb', '雷灵草', 'material', 1, true],
    ['bloodHerb', '血灵草', 'material', 1, true],
    ['spiritCarp', '灵鲤', 'material', 1, true],
    ['spiritShrimp', '灵虾', 'material', 1, true],
    ['silverTrout', '银鳟', 'material', 1, true],
    ['greenBass', '青鲈', 'material', 1, true],
    ['darkCatfish', '玄鲶', 'material', 1, true],
    ['sunsetSalmon', '霞鲑', 'material', 1, true],
    ['thunderEel', '雷鳗', 'material', 1, true],
    ['spiritLobster', '灵龙虾', 'material', 1, true],
    ['swordfish', '剑鱼', 'material', 1, true],
    ['dragonFish', '龙鱼', 'material', 1, true],
    ['lingzhi', '灵芝', 'material', 1, true],
    ['spiritMushroom', '灵菇', 'material', 1, true],
    ['skySilk', '天蚕丝', 'material', 1, true],
    ['ironhideGrass', '铁皮草', 'material', 1, true],
    ['dragonSalivaGrass', '龙涎草', 'material', 1, true],
    ['moonSpiritGrass', '月灵草', 'material', 1, true],
    ['starGrass', '星辰草', 'material', 1, true],
    ['bloodSpiritGrass', '血灵草', 'material', 1, true],
    ['thunderSpiritGrass', '雷灵草', 'material', 1, true],
    ['goldenLingzhi', '金芝', 'material', 1, true],
    ['qiGatheringGrass', '聚气草', 'material', 1, true],
    ['heartClearGrass', '清心草', 'material', 1, true],
    ['spiritHoney', '灵蜜', 'material', 1, true],
    ['spiritRice', '灵米', 'material', 1, true],
    ['bloodGinsengFruit', '血参果', 'material', 1, true],
    ['oldGinseng', '老山参', 'material', 1, true],
    ['commonSeed', '凡灵种', 'material', 1, true],
    ['fineSeed', '上品灵种', 'material', 1, true],
    ['rareSeed', '极品灵种', 'material', 1, true],
    ['lingshi', '灵石', 'material', 1, true],
    ['fishBox', '鱼宝箱', 'material', 1, true],
    ['healingPill', '疗伤丹', 'consumable', 5, true],
    ['qiGatheringPill', '聚气丹', 'consumable', 5, true],
    ['foundationPill', '筑基丹', 'consumable', 5, true],
    ['goldCorePill', '结金丹', 'consumable', 5, true],
    ['nascentSoulPill', '化婴丹', 'consumable', 5, true],
    ['spiritTransformationPill', '化神丹', 'consumable', 5, true],
    ['voidRefiningPill', '炼虚丹', 'consumable', 5, true],
    ['bodyIntegrationPill', '合体丹', 'consumable', 5, true],
    ['mahayanaPill', '大乘丹', 'consumable', 5, true],
    ['copperSword', '赤铜剑', 'equipment', 10, true],
    ['ironSword', '玄铁剑', 'equipment', 10, true],
    ['silverArmor', '银鳞甲', 'equipment', 10, true],
    ['spiritStaff', '灵木杖', 'equipment', 10, true],
    ['darkIronBlade', '玄铁刃', 'equipment', 10, true],
    ['formationBase', '阵基', 'material', 1, true],
    ['grilledCarp', '烤灵鲤', 'consumable', 5, true],
    ['shrimpSoup', '灵虾汤', 'consumable', 5, true],
    ['spiritRiceMeal', '灵米饭', 'consumable', 5, true],
    ['troutFeast', '银鳟宴', 'consumable', 5, true],
    ['lobsterBanquet', '灵龙虾宴', 'consumable', 5, true],
    ['dragonFishBanquet', '龙鱼宴', 'consumable', 5, true],
    ['beastFeed', '灵兽口粮', 'consumable', 5, true],
    ['talismanPaper', '空白符纸', 'consumable', 5, true],
    ['gatheringTalisman', '采灵符', 'consumable', 5, true],
    ['hasteTalisman', '疾行符', 'consumable', 5, true],
    ['wardTalisman', '护身符', 'consumable', 5, true],
    ['healingTalisman', '回春符', 'consumable', 5, true],
    ['beastLureTalisman', '引兽符', 'consumable', 5, true],
    ['gatheringFormation', '聚材阵', 'equipment', 10, true],
    ['farmlandFormation', '丰壤阵', 'equipment', 10, true],
    ['fishingFormation', '回澜阵', 'equipment', 10, true],
    ['craftingFormation', '百工阵', 'equipment', 10, true],
    ['beastFormation', '御灵阵', 'equipment', 10, true],
    ['herbBundle', '散装药材', 'material', 1, true],
    ['oreBundle', '散装灵矿', 'material', 1, true],
    ['woodBundle', '散装木料', 'material', 1, true],
    ['foodBundle', '散装食材', 'material', 1, true]
  ],

  gathering: {
    mining: [
      ['copper', '铜矿脉', 1, 4, 12, 15, 30,
        [['copperOre', 100, 1], ['topaz', 8, 1], ['lingshi', 8, 1]]],
      ['tin', '锡矿脉', 1, 4, 12, 15, 30,
        [['tinOre', 100, 1], ['topaz', 8, 1], ['lingshi', 8, 1]]],
      ['iron', '铁矿脉', 1, 4, 12, 15, 30,
        [['ironOre', 100, 1], ['topaz', 8, 1], ['lingshi', 9, 1]]],
      ['silver', '银矿脉', 12, 6, 25, 12, 25,
        [['silverOre', 100, 1], ['topaz', 8, 1], ['lingshi', 10, 1]]],
      ['gold', '金矿脉', 20, 8, 40, 10, 22,
        [['goldOre', 100, 1], ['topaz', 6, 1], ['sapphire', 3, 1], ['lingshi', 12, 1]]],
      ['mithril', '秘银矿脉', 25, 9, 50, 9, 20,
        [['mithrilOre', 100, 1], ['sapphire', 8, 1], ['ruby', 3, 1], ['lingshi', 12, 1]]],
      ['jade', '灵玉矿脉', 30, 10, 60, 8, 18,
        [['jadeShard', 100, 1], ['sapphire', 8, 1], ['ruby', 3, 1], ['lingshi', 13, 1]]],
      ['adamant', '精金矿脉', 35, 11, 70, 7, 15,
        [['adamantOre', 100, 1], ['ruby', 7, 1], ['emerald', 6, 1],
          ['diamond', 2, 1], ['lingshi', 14, 1]]],
      ['darkiron', '玄铁矿脉', 40, 12, 85, 6, 12,
        [['darkIronOre', 100, 1], ['ruby', 6, 1], ['emerald', 6, 1],
          ['diamond', 3, 1], ['darkCrystal', 1, 1], ['lingshi', 15, 1]]],
      ['crystal', '玄晶矿脉', 45, 14, 100, 5, 10,
        [['crystalOre', 100, 1], ['ruby', 6, 1], ['emerald', 6, 1],
          ['diamond', 3, 1], ['darkCrystal', 2, 1], ['lingshi', 17, 1]]]
    ],
    woodcutting: [
      ['willow', '河畔柳林', 1, 4, 10, 15, 30,
        [['willowWood', 70, 1], ['pineWood', 15, 1], ['spiritPeach', 8, 1],
          ['lingshi', 10, 1], ['birdNest', 5, 1], ['commonSeed', 6, 1]]],
      ['pine', '青松岭', 5, 5, 15, 12, 25,
        [['pineWood', 65, 1], ['willowWood', 15, 1], ['spiritPeach', 8, 1],
          ['lingshi', 10, 1], ['birdNest', 3, 1], ['commonSeed', 6, 1]]],
      ['peach', '桃花谷', 12, 6, 22, 10, 22,
        [['peachWood', 60, 1], ['pineWood', 15, 1], ['spiritPeach', 8, 1],
          ['lingshi', 10, 1], ['birdNest', 3, 1], ['commonSeed', 6, 1]]],
      ['nanmu', '楠木深林', 20, 8, 35, 8, 18,
        [['nanmuWood', 55, 1], ['peachWood', 15, 1], ['spiritPeach', 8, 1],
          ['lingshi', 12, 1], ['resin', 10, 1], ['birdNest', 8, 1], ['commonSeed', 6, 1]]],
      ['phoenix', '梧桐灵谷', 28, 10, 48, 7, 15,
        [['phoenixWood', 50, 1], ['nanmuWood', 18, 1], ['spiritPeach', 6, 1],
          ['lingshi', 12, 1], ['spiritEgg', 10, 1], ['resin', 10, 1],
          ['birdNest', 6, 1], ['fineSeed', 5, 1]]],
      ['spirit', '灵木幽林', 35, 11, 60, 6, 14,
        [['spiritWood', 50, 1], ['phoenixWood', 15, 1], ['spiritPeach', 6, 1],
          ['lingshi', 12, 1], ['spiritWormSilk', 10, 1], ['resin', 8, 1],
          ['birdNest', 5, 1], ['fineSeed', 5, 1]]],
      ['thunder', '雷劈枯林', 42, 13, 78, 5, 12,
        [['thunderWood', 45, 1], ['spiritWood', 18, 1], ['spiritPeach', 6, 1],
          ['lingshi', 15, 1], ['thunderHerb', 10, 1], ['resin', 7, 1],
          ['birdNest', 5, 1], ['beastHide', 6, 1], ['spiritFruit', 5, 1],
          ['rareSeed', 5, 1]]],
      ['blood', '血檀秘境', 48, 14, 90, 4, 10,
        [['bloodSandalwood', 45, 1], ['thunderWood', 15, 1], ['spiritPeach', 6, 1],
          ['lingshi', 15, 1], ['beastHide', 10, 1], ['bloodHerb', 8, 1],
          ['resin', 7, 1], ['birdNest', 5, 1], ['spiritFruit', 5, 1],
          ['rareSeed', 5, 1]]],
      ['ancient', '万年古林', 55, 16, 110, 3, 8,
        [['ancientWood', 40, 1], ['bloodSandalwood', 15, 1], ['spiritWood', 12, 1],
          ['lingshi', 15, 1], ['millenniumVine', 8, 1], ['spiritFruit', 5, 1],
          ['birdNest', 5, 1], ['beastHide', 6, 1], ['rareSeed', 5, 1]]],
      ['vine', '仙藤圣林', 62, 18, 140, 3, 7,
        [['millenniumVine', 35, 1], ['ancientWood', 18, 1], ['spiritWood', 12, 1],
          ['lingshi', 15, 1], ['spiritFruit', 8, 1], ['resin', 7, 1],
          ['birdNest', 5, 1], ['beastHide', 6, 1], ['rareSeed', 5, 1]]]
    ],
    herb: [],
    fishing: [
      ['pond', '村口池塘', 1, 4, 10,
        [['spiritCarp', 70, 1], ['spiritShrimp', 30, 1]]],
      ['shallow', '灵溪浅滩', 5, 3.5, 15,
        [['spiritShrimp', 60, 1], ['spiritCarp', 25, 1], ['silverTrout', 15, 1]]],
      ['moon', '银月溪谷', 10, 5, 22,
        [['silverTrout', 55, 1], ['spiritCarp', 25, 1],
          ['greenBass', 15, 1], ['spiritShrimp', 5, 1]]],
      ['deep', '翠玉深潭', 18, 6, 32,
        [['greenBass', 50, 1], ['silverTrout', 25, 1],
          ['darkCatfish', 15, 1], ['spiritCarp', 10, 1]]],
      ['dark', '幽冥暗河', 25, 7, 42,
        [['darkCatfish', 50, 1], ['greenBass', 25, 1],
          ['sunsetSalmon', 15, 1], ['thunderEel', 10, 1]]],
      ['waterfall', '落霞瀑布', 32, 8, 55,
        [['sunsetSalmon', 50, 1], ['darkCatfish', 20, 1],
          ['thunderEel', 18, 1], ['greenBass', 12, 1]]],
      ['thunderPond', '雷泽沼地', 40, 9, 68,
        [['thunderEel', 50, 1], ['sunsetSalmon', 22, 1],
          ['spiritLobster', 15, 1], ['darkCatfish', 13, 1]]],
      ['ocean', '沧澜深海', 50, 10, 85,
        [['spiritLobster', 45, 1], ['thunderEel', 25, 1],
          ['swordfish', 18, 1], ['sunsetSalmon', 12, 1]]],
      ['trench', '剑渊海沟', 60, 12, 105,
        [['swordfish', 45, 1], ['spiritLobster', 25, 1],
          ['dragonFish', 12, 1], ['thunderEel', 18, 1]]],
      ['dragon', '龙渊秘境', 70, 15, 130,
        [['dragonFish', 40, 1], ['swordfish', 25, 1],
          ['spiritLobster', 20, 1], ['thunderEel', 15, 1]]]
    ]
  },

  explorations: [
    ['mining', 'explore:mining', '探寻灵矿', '探索', 2, 10, 5, 1],
    ['woodcutting', 'explore:woodcutting', '探寻灵林', '探索', 2, 10, 5, 1],
    ['herb', 'explore:herb', '探寻药田', '探索', 2, 10, 5, 1]
  ],

  fishSpecies: [
    ['spiritCarp', '灵鲤', 'fishing:spiritCarp', 20, 60],
    ['spiritShrimp', '灵虾', 'fishing:spiritShrimp', 20, 60],
    ['silverTrout', '银鳟', 'fishing:silverTrout', 20, 60],
    ['greenBass', '青鲈', 'fishing:greenBass', 20, 60],
    ['darkCatfish', '玄鲶', 'fishing:darkCatfish', 20, 60],
    ['sunsetSalmon', '霞鲑', 'fishing:sunsetSalmon', 20, 60],
    ['thunderEel', '雷鳗', 'fishing:thunderEel', 20, 60],
    ['spiritLobster', '灵龙虾', 'fishing:spiritLobster', 20, 60],
    ['swordfish', '剑鱼', 'fishing:swordfish', 20, 60],
    ['dragonFish', '龙鱼', 'fishing:dragonFish', 20, 60]
  ],

  recipes: [
    ['alchemy:healingPill', 'alchemy', 'alchemy:healingPill', '疗伤丹', 1, 8,
      { lingzhi: 2 }, [], { itemId: 'healingPill', quantity: 1 }],
    ['alchemy:qiGatheringPill', 'alchemy', 'alchemy:qiGatheringPill', '聚气丹', 5, 10,
      { qiGatheringGrass: 2, spiritHoney: 1 }, [], { itemId: 'qiGatheringPill', quantity: 1 }],
    ['alchemy:foundationPill', 'alchemy', 'alchemy:foundationPill', '筑基丹', 15, 16,
      { ironhideGrass: 3, skySilk: 1, spiritHoney: 1 }, [], { itemId: 'foundationPill', quantity: 1 }],
    ['alchemy:goldCorePill', 'alchemy', 'alchemy:goldCorePill', '结金丹', 35, 24,
      { dragonSalivaGrass: 3, moonSpiritGrass: 2, goldOre: 1 }, [], { itemId: 'goldCorePill', quantity: 1 }],
    ['alchemy:nascentSoulPill', 'alchemy', 'alchemy:nascentSoulPill', '化婴丹', 50, 36,
      { starGrass: 3, goldenLingzhi: 1, jadeShard: 1 }, [], { itemId: 'nascentSoulPill', quantity: 1 }],
    ['alchemy:spiritTransformationPill', 'alchemy', 'alchemy:spiritTransformationPill', '化神丹', 65, 50,
      { thunderSpiritGrass: 3, goldenLingzhi: 2, crystalOre: 1 }, [],
      { itemId: 'spiritTransformationPill', quantity: 1 }],
    ['alchemy:voidRefiningPill', 'alchemy', 'alchemy:voidRefiningPill', '炼虚丹', 75, 64,
      { bloodSpiritGrass: 3, millenniumVine: 1, darkCrystal: 1 }, [],
      { itemId: 'voidRefiningPill', quantity: 1 }],
    ['alchemy:bodyIntegrationPill', 'alchemy', 'alchemy:bodyIntegrationPill', '合体丹', 85, 80,
      { goldenLingzhi: 3, dragonFish: 1, adamantOre: 2 }, [],
      { itemId: 'bodyIntegrationPill', quantity: 1 }],
    ['alchemy:mahayanaPill', 'alchemy', 'alchemy:mahayanaPill', '大乘丹', 95, 100,
      { goldenLingzhi: 5, dragonFish: 2, darkCrystal: 2 }, [],
      { itemId: 'mahayanaPill', quantity: 1 }],

    ['forging:copperSword', 'forging', 'forging:copperSword', '赤铜剑', 1, 10,
      { copperOre: 3, willowWood: 1 }, [], { itemId: 'copperSword', quantity: 1 }],
    ['forging:ironSword', 'forging', 'forging:ironSword', '玄铁剑', 10, 16,
      { ironOre: 5, pineWood: 2 }, [], { itemId: 'ironSword', quantity: 1 }],
    ['forging:silverArmor', 'forging', 'forging:silverArmor', '银鳞甲', 20, 24,
      { silverOre: 8, beastHide: 2 }, [], { itemId: 'silverArmor', quantity: 1 }],
    ['forging:spiritStaff', 'forging', 'forging:spiritStaff', '灵木杖', 35, 32,
      { spiritWood: 5, jadeShard: 2 }, [], { itemId: 'spiritStaff', quantity: 1 }],
    ['forging:darkIronBlade', 'forging', 'forging:darkIronBlade', '玄铁刃', 55, 45,
      { darkIronOre: 8, thunderWood: 2 }, [], { itemId: 'darkIronBlade', quantity: 1 }],
    ['forging:formationBase', 'forging', 'forging:formationBase', '阵基', 20, 20,
      { jadeShard: 3, spiritWood: 3 }, [], { itemId: 'formationBase', quantity: 1 }],

    ['cooking:grilledCarp', 'cooking', 'cooking:grilledCarp', '烤灵鲤', 1, 6,
      { spiritCarp: 2 }, [], { itemId: 'grilledCarp', quantity: 1 }],
    ['cooking:troutFeast', 'cooking', 'cooking:troutFeast', '银鳟宴', 12, 8,
      { silverTrout: 2 }, [], { itemId: 'troutFeast', quantity: 1 }],
    ['cooking:lobsterBanquet', 'cooking', 'cooking:lobsterBanquet', '灵龙虾宴', 40, 14,
      { spiritLobster: 2 }, [], { itemId: 'lobsterBanquet', quantity: 1 }],
    ['cooking:dragonFishBanquet', 'cooking', 'cooking:dragonFishBanquet', '龙鱼宴', 70, 22,
      { dragonFish: 2 }, [], { itemId: 'dragonFishBanquet', quantity: 1 }],
    ['cooking:spiritRiceMeal', 'cooking', 'cooking:spiritRiceMeal', '灵米饭', 10, 10,
      { spiritRice: 3, spiritHoney: 1 }, [], { itemId: 'spiritRiceMeal', quantity: 1 }],
    ['cooking:beastFeed', 'cooking', 'cooking:beastFeed', '灵兽口粮', 12, 10,
      { spiritRice: 2 }, [{ quantity: 1, itemIds: ['spiritCarp'] }],
      { itemId: 'beastFeed', quantity: 2 }],

    ['talisman:talismanPaper', 'talisman', 'talisman:talismanPaper', '空白符纸', 1, 8,
      { willowWood: 2 }, [], { itemId: 'talismanPaper', quantity: 4 }],
    ['talisman:gatheringTalisman', 'talisman', 'talisman:gatheringTalisman', '采灵符', 5, 10,
      { talismanPaper: 1, lingzhi: 1 }, [], { itemId: 'gatheringTalisman', quantity: 1 }],
    ['talisman:hasteTalisman', 'talisman', 'talisman:hasteTalisman', '疾行符', 20, 16,
      { talismanPaper: 1, thunderHerb: 1 }, [], { itemId: 'hasteTalisman', quantity: 1 }],
    ['talisman:wardTalisman', 'talisman', 'talisman:wardTalisman', '护身符', 15, 14,
      { talismanPaper: 1, ironOre: 1 }, [], { itemId: 'wardTalisman', quantity: 1 }],
    ['talisman:healingTalisman', 'talisman', 'talisman:healingTalisman', '回春符', 25, 18,
      { talismanPaper: 1, heartClearGrass: 1 }, [], { itemId: 'healingTalisman', quantity: 1 }],
    ['talisman:beastLureTalisman', 'talisman', 'talisman:beastLureTalisman', '引兽符', 30, 22,
      { talismanPaper: 1, spiritFruit: 1 }, [], { itemId: 'beastLureTalisman', quantity: 1 }],

    ['formation:gatheringFormation', 'formation', 'formation:gatheringFormation', '聚材阵', 20, 40,
      { formationBase: 1, spiritWood: 3, qiGatheringGrass: 2 }, [],
      { itemId: 'gatheringFormation', quantity: 1 }],
    ['formation:farmlandFormation', 'formation', 'formation:farmlandFormation', '丰壤阵', 25, 45,
      { formationBase: 1, spiritRice: 5, moonSpiritGrass: 2 }, [],
      { itemId: 'farmlandFormation', quantity: 1 }],
    ['formation:fishingFormation', 'formation', 'formation:fishingFormation', '回澜阵', 30, 50,
      { formationBase: 1, jadeShard: 2, spiritCarp: 5 }, [],
      { itemId: 'fishingFormation', quantity: 1 }],
    ['formation:craftingFormation', 'formation', 'formation:craftingFormation', '百工阵', 40, 60,
      { formationBase: 1, darkIronOre: 2, starGrass: 2 }, [],
      { itemId: 'craftingFormation', quantity: 1 }],
    ['formation:beastFormation', 'formation', 'formation:beastFormation', '御灵阵', 45, 70,
      { formationBase: 1, beastHide: 2, spiritEgg: 2 }, [],
      { itemId: 'beastFormation', quantity: 1 }]
  ],

  crops: [
    ['spiritRice', '灵米', 1, { itemId: 'commonSeed', quantity: 1 }, 300,
      { itemId: 'spiritRice', quantity: 4 }],
    ['qiGatheringGrass', '聚气草', 3, { itemId: 'commonSeed', quantity: 1 }, 600,
      { itemId: 'qiGatheringGrass', quantity: 3 }],
    ['heartClearGrass', '清心草', 8, { itemId: 'commonSeed', quantity: 1 }, 900,
      { itemId: 'heartClearGrass', quantity: 3 }],
    ['moonSpiritGrass', '月灵草', 20, { itemId: 'fineSeed', quantity: 1 }, 1800,
      { itemId: 'moonSpiritGrass', quantity: 3 }],
    ['bloodSpiritGrass', '血灵草', 35, { itemId: 'fineSeed', quantity: 1 }, 2700,
      { itemId: 'bloodSpiritGrass', quantity: 2 }],
    ['goldenLingzhi', '金芝', 50, { itemId: 'rareSeed', quantity: 1 }, 5400,
      { itemId: 'goldenLingzhi', quantity: 1 }]
  ],

  formations: [
    ['gatheringFormation', 'gatheringFormation', 'formation:gatheringFormation', '聚材阵',
      'gatheringExtraYieldChance', 0.05],
    ['farmlandFormation', 'farmlandFormation', 'formation:farmlandFormation', '丰壤阵',
      'farmGrowthReduction', 0.10],
    ['fishingFormation', 'fishingFormation', 'formation:fishingFormation', '回澜阵',
      'fishRecoveryReduction', 0.10],
    ['craftingFormation', 'craftingFormation', 'formation:craftingFormation', '百工阵',
      'craftingDurationReduction', 0.05],
    ['beastFormation', 'beastFormation', 'formation:beastFormation', '御灵阵',
      'beastTrainingXpBonus', 0.10]
  ],

  beasts: [
    ['spiritFox', '灵狐', 'herb', 'beastTaming:spiritFox', 0.01,
      60, 'beastLureTalisman', 30, 15, 5,
      30, 'beastFeed', 10, 10, 5, 2,
      'gatheringExtraYieldChance', 'herb', 0.05],
    ['rockshell', '岩甲兽', 'mining', 'beastTaming:rockshell', 0.01,
      60, 'beastLureTalisman', 30, 15, 5,
      30, 'beastFeed', 10, 10, 5, 2,
      'gatheringExtraYieldChance', 'mining', 0.05],
    ['azureCrane', '青羽鹤', 'woodcutting', 'beastTaming:azureCrane', 0.01,
      60, 'beastLureTalisman', 30, 15, 5,
      30, 'beastFeed', 10, 10, 5, 2,
      'gatheringDurationReduction', 'woodcutting', 0.05],
    ['waterTurtle', '水灵龟', 'fishing', 'beastTaming:waterTurtle', 0.01,
      60, 'beastLureTalisman', 30, 15, 5,
      30, 'beastFeed', 10, 10, 5, 2,
      'fishRecoveryReduction', null, 0.10]
  ],

  traits: [
    ['keenNose', '灵嗅', 'gatheringExtraYieldChance', 0.02],
    ['diligent', '勤勉', 'beastTrainingXpBonus', 0.10],
    ['deftPaws', '巧爪', 'materialRetentionChance', 0.02],
    ['friendly', '亲和', 'socialPositiveGainBonus', 0.05]
  ],

  growthTendencies: [
    ['steady', '稳健', 1, 1],
    ['swift', '敏捷', 0.90, 1],
    ['spiritual', '灵慧', 1.10, 1.10]
  ]
});
