(function (root, factory) {
  'use strict';
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else if (root) root.ItemArtContent = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  function deepFreeze(value) {
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.freeze(value);
    Object.keys(value).forEach(function (key) { deepFreeze(value[key]); });
    return value;
  }

  const ICONS = {
    "adamantArmorPlate": {"name":"精金法甲片","icon100":"assets/item-icons/100/adamantArmorPlate.png","icon50":"assets/item-icons/50/adamantArmorPlate.png","batch":"p1-v4-no-outline"},
    "adamantBar": {"name":"精金锭","icon100":"assets/item-icons/100/adamantBar.png","icon50":"assets/item-icons/50/adamantBar.png","batch":"p1-v4-no-outline"},
    "adamantBootBlank": {"name":"精金踏云履胚","icon100":"assets/item-icons/100/adamantBootBlank.png","icon50":"assets/item-icons/50/adamantBootBlank.png","batch":"p1-v4-no-outline"},
    "adamantBracerBlank": {"name":"精金护腕胚","icon100":"assets/item-icons/100/adamantBracerBlank.png","icon50":"assets/item-icons/50/adamantBracerBlank.png","batch":"p1-v4-no-outline"},
    "adamantCrownBlank": {"name":"精金法冠胚","icon100":"assets/item-icons/100/adamantCrownBlank.png","icon50":"assets/item-icons/50/adamantCrownBlank.png","batch":"p1-v4-no-outline"},
    "adamantDaggerBlank": {"name":"精金短刃胚","icon100":"assets/item-icons/100/adamantDaggerBlank.png","icon50":"assets/item-icons/50/adamantDaggerBlank.png","batch":"p1-v4-no-outline"},
    "adamantHeavyBladeBlank": {"name":"精金重剑胚","icon100":"assets/item-icons/100/adamantHeavyBladeBlank.png","icon50":"assets/item-icons/50/adamantHeavyBladeBlank.png","batch":"p1-v4-no-outline"},
    "adamantOre": {"name":"精金矿","icon100":"assets/item-icons/100/adamantOre.svg","icon50":"assets/item-icons/50/adamantOre.svg","batch":"runtime-mining-flat-svg"},
    "adamantShieldCore": {"name":"精金护符盾核","icon100":"assets/item-icons/100/adamantShieldCore.png","icon50":"assets/item-icons/50/adamantShieldCore.png","batch":"p1-v4-no-outline"},
    "adamantSwordBlank": {"name":"精金飞剑胚","icon100":"assets/item-icons/100/adamantSwordBlank.png","icon50":"assets/item-icons/50/adamantSwordBlank.png","batch":"p1-v4-no-outline"},
    "artisanPouch": {"name":"匠材包","icon100":"assets/item-icons/100/artisanPouch.png","icon50":"assets/item-icons/50/artisanPouch.png","batch":"p1-v4-no-outline"},
    "azureJade": {"name":"青空玉","icon100":"assets/item-icons/100/azureJade.png","icon50":"assets/item-icons/50/azureJade.png","batch":"p2-v4-no-outline"},
    "barrentoeHerb": {"name":"寂趾草","icon100":"assets/item-icons/100/barrentoeHerb.png","icon50":"assets/item-icons/50/barrentoeHerb.png","batch":"p2-v4-no-outline"},
    "barrentoeSeed": {"name":"寂趾籽","icon100":"assets/item-icons/100/barrentoeSeed.png","icon50":"assets/item-icons/50/barrentoeSeed.png","batch":"p2-v4-no-outline"},
    "beastBone": {"name":"妖兽骨","icon100":"assets/item-icons/100/beastBone.png","icon50":"assets/item-icons/50/beastBone.png","batch":"p0-v4-no-outline"},
    "brokenFang": {"name":"断裂兽牙","icon100":"assets/item-icons/100/brokenFang.png","icon50":"assets/item-icons/50/brokenFang.png","batch":"p0-v4-no-outline"},
    "bronzeArmorPlate": {"name":"灵铜法甲片","icon100":"assets/item-icons/100/bronzeArmorPlate.png","icon50":"assets/item-icons/50/bronzeArmorPlate.png","batch":"p0-v4-no-outline"},
    "bronzeBar": {"name":"灵铜锭","icon100":"assets/item-icons/100/bronzeBar.png","icon50":"assets/item-icons/50/bronzeBar.png","batch":"p0-v4-no-outline"},
    "bronzeBootBlank": {"name":"灵铜踏云履胚","icon100":"assets/item-icons/100/bronzeBootBlank.png","icon50":"assets/item-icons/50/bronzeBootBlank.png","batch":"p0-v4-no-outline"},
    "bronzeBracerBlank": {"name":"灵铜护腕胚","icon100":"assets/item-icons/100/bronzeBracerBlank.png","icon50":"assets/item-icons/50/bronzeBracerBlank.png","batch":"p0-v4-no-outline"},
    "bronzeCrownBlank": {"name":"灵铜法冠胚","icon100":"assets/item-icons/100/bronzeCrownBlank.png","icon50":"assets/item-icons/50/bronzeCrownBlank.png","batch":"p0-v4-no-outline"},
    "bronzeDaggerBlank": {"name":"灵铜短刃胚","icon100":"assets/item-icons/100/bronzeDaggerBlank.png","icon50":"assets/item-icons/50/bronzeDaggerBlank.png","batch":"p0-v4-no-outline"},
    "bronzeHeavyBladeBlank": {"name":"灵铜重剑胚","icon100":"assets/item-icons/100/bronzeHeavyBladeBlank.png","icon50":"assets/item-icons/50/bronzeHeavyBladeBlank.png","batch":"p0-v4-no-outline"},
    "bronzeShieldCore": {"name":"灵铜护符盾核","icon100":"assets/item-icons/100/bronzeShieldCore.png","icon50":"assets/item-icons/50/bronzeShieldCore.png","batch":"p0-v4-no-outline"},
    "bronzeSwordBlank": {"name":"灵铜飞剑胚","icon100":"assets/item-icons/100/bronzeSwordBlank.png","icon50":"assets/item-icons/50/bronzeSwordBlank.png","batch":"p0-v4-no-outline"},
    "coalOre": {"name":"灵炭矿","icon100":"assets/item-icons/100/coalOre.png","icon50":"assets/item-icons/50/coalOre.png","batch":"p1-v4-no-outline"},
    "copperOre": {"name":"铜矿石","icon100":"assets/item-icons/100/copperOre.svg","icon50":"assets/item-icons/50/copperOre.svg","batch":"runtime-mining-flat-svg"},
    "crystalArmorPlate": {"name":"灵晶法甲片","icon100":"assets/item-icons/100/crystalArmorPlate.png","icon50":"assets/item-icons/50/crystalArmorPlate.png","batch":"p2-v4-no-outline"},
    "crystalBar": {"name":"灵晶锭","icon100":"assets/item-icons/100/crystalBar.png","icon50":"assets/item-icons/50/crystalBar.png","batch":"p2-v4-no-outline"},
    "crystalBootBlank": {"name":"灵晶踏云履胚","icon100":"assets/item-icons/100/crystalBootBlank.png","icon50":"assets/item-icons/50/crystalBootBlank.png","batch":"p2-v4-no-outline"},
    "crystalBracerBlank": {"name":"灵晶护腕胚","icon100":"assets/item-icons/100/crystalBracerBlank.png","icon50":"assets/item-icons/50/crystalBracerBlank.png","batch":"p2-v4-no-outline"},
    "crystalCrownBlank": {"name":"灵晶法冠胚","icon100":"assets/item-icons/100/crystalCrownBlank.png","icon50":"assets/item-icons/50/crystalCrownBlank.png","batch":"p2-v4-no-outline"},
    "crystalDaggerBlank": {"name":"灵晶短刃胚","icon100":"assets/item-icons/100/crystalDaggerBlank.png","icon50":"assets/item-icons/50/crystalDaggerBlank.png","batch":"p2-v4-no-outline"},
    "crystalHeavyBladeBlank": {"name":"灵晶重剑胚","icon100":"assets/item-icons/100/crystalHeavyBladeBlank.png","icon50":"assets/item-icons/50/crystalHeavyBladeBlank.png","batch":"p2-v4-no-outline"},
    "crystalOre": {"name":"玄晶矿","icon100":"assets/item-icons/100/crystalOre.svg","icon50":"assets/item-icons/50/crystalOre.svg","batch":"runtime-mining-flat-svg"},
    "crystalShieldCore": {"name":"灵晶护符盾核","icon100":"assets/item-icons/100/crystalShieldCore.png","icon50":"assets/item-icons/50/crystalShieldCore.png","batch":"p2-v4-no-outline"},
    "crystalSwordBlank": {"name":"灵晶飞剑胚","icon100":"assets/item-icons/100/crystalSwordBlank.png","icon50":"assets/item-icons/50/crystalSwordBlank.png","batch":"p2-v4-no-outline"},
    "darkCrystal": {"name":"暗晶","icon100":"assets/item-icons/100/darkCrystal.svg","icon50":"assets/item-icons/50/darkCrystal.svg","batch":"runtime-mining-flat-svg"},
    "darkIronArmorPlate": {"name":"玄铁法甲片","icon100":"assets/item-icons/100/darkIronArmorPlate.png","icon50":"assets/item-icons/50/darkIronArmorPlate.png","batch":"p2-v4-no-outline"},
    "darkIronBar": {"name":"玄铁锭","icon100":"assets/item-icons/100/darkIronBar.png","icon50":"assets/item-icons/50/darkIronBar.png","batch":"p2-v4-no-outline"},
    "darkIronBootBlank": {"name":"玄铁踏云履胚","icon100":"assets/item-icons/100/darkIronBootBlank.png","icon50":"assets/item-icons/50/darkIronBootBlank.png","batch":"p2-v4-no-outline"},
    "darkIronBracerBlank": {"name":"玄铁护腕胚","icon100":"assets/item-icons/100/darkIronBracerBlank.png","icon50":"assets/item-icons/50/darkIronBracerBlank.png","batch":"p2-v4-no-outline"},
    "darkIronCrownBlank": {"name":"玄铁法冠胚","icon100":"assets/item-icons/100/darkIronCrownBlank.png","icon50":"assets/item-icons/50/darkIronCrownBlank.png","batch":"p2-v4-no-outline"},
    "darkIronDaggerBlank": {"name":"玄铁短刃胚","icon100":"assets/item-icons/100/darkIronDaggerBlank.png","icon50":"assets/item-icons/50/darkIronDaggerBlank.png","batch":"p2-v4-no-outline"},
    "darkIronHeavyBladeBlank": {"name":"玄铁重剑胚","icon100":"assets/item-icons/100/darkIronHeavyBladeBlank.png","icon50":"assets/item-icons/50/darkIronHeavyBladeBlank.png","batch":"p2-v4-no-outline"},
    "darkIronOre": {"name":"玄铁矿","icon100":"assets/item-icons/100/darkIronOre.svg","icon50":"assets/item-icons/50/darkIronOre.svg","batch":"runtime-mining-flat-svg"},
    "darkIronShieldCore": {"name":"玄铁护符盾核","icon100":"assets/item-icons/100/darkIronShieldCore.png","icon50":"assets/item-icons/50/darkIronShieldCore.png","batch":"p2-v4-no-outline"},
    "darkIronSwordBlank": {"name":"玄铁飞剑胚","icon100":"assets/item-icons/100/darkIronSwordBlank.png","icon50":"assets/item-icons/50/darkIronSwordBlank.png","batch":"p2-v4-no-outline"},
    "diamond": {"name":"金钻","icon100":"assets/item-icons/100/diamond.svg","icon50":"assets/item-icons/50/diamond.svg","batch":"runtime-mining-flat-svg"},
    "dragoniteBar": {"name":"龙纹锭","icon100":"assets/item-icons/100/dragoniteBar.png","icon50":"assets/item-icons/50/dragoniteBar.png","batch":"p2-v4-no-outline"},
    "dragoniteOre": {"name":"龙纹矿","icon100":"assets/item-icons/100/dragoniteOre.png","icon50":"assets/item-icons/50/dragoniteOre.png","batch":"p2-v4-no-outline"},
    "emerald": {"name":"翠玉","icon100":"assets/item-icons/100/emerald.svg","icon50":"assets/item-icons/50/emerald.svg","batch":"runtime-mining-flat-svg"},
    "fiendBlood": {"name":"邪魔血","icon100":"assets/item-icons/100/fiendBlood.png","icon50":"assets/item-icons/50/fiendBlood.png","batch":"p2-v4-no-outline"},
    "garumHerb": {"name":"嘉露草","icon100":"assets/item-icons/100/garumHerb.png","icon50":"assets/item-icons/50/garumHerb.png","batch":"p0-v4-no-outline"},
    "garumSeed": {"name":"嘉露种子","icon100":"assets/item-icons/100/garumSeed.png","icon50":"assets/item-icons/50/garumSeed.png","batch":"p0-v4-no-outline"},
    "goldArmorPlate": {"name":"赤金法甲片","icon100":"assets/item-icons/100/goldArmorPlate.png","icon50":"assets/item-icons/50/goldArmorPlate.png","batch":"p1-v4-no-outline"},
    "goldBar": {"name":"赤金锭","icon100":"assets/item-icons/100/goldBar.png","icon50":"assets/item-icons/50/goldBar.png","batch":"p1-v4-no-outline"},
    "goldBootBlank": {"name":"赤金踏云履胚","icon100":"assets/item-icons/100/goldBootBlank.png","icon50":"assets/item-icons/50/goldBootBlank.png","batch":"p1-v4-no-outline"},
    "goldBracerBlank": {"name":"赤金护腕胚","icon100":"assets/item-icons/100/goldBracerBlank.png","icon50":"assets/item-icons/50/goldBracerBlank.png","batch":"p1-v4-no-outline"},
    "goldCrownBlank": {"name":"赤金法冠胚","icon100":"assets/item-icons/100/goldCrownBlank.png","icon50":"assets/item-icons/50/goldCrownBlank.png","batch":"p1-v4-no-outline"},
    "goldDaggerBlank": {"name":"赤金短刃胚","icon100":"assets/item-icons/100/goldDaggerBlank.png","icon50":"assets/item-icons/50/goldDaggerBlank.png","batch":"p1-v4-no-outline"},
    "goldHeavyBladeBlank": {"name":"赤金重剑胚","icon100":"assets/item-icons/100/goldHeavyBladeBlank.png","icon50":"assets/item-icons/50/goldHeavyBladeBlank.png","batch":"p1-v4-no-outline"},
    "goldOre": {"name":"金矿石","icon100":"assets/item-icons/100/goldOre.svg","icon50":"assets/item-icons/50/goldOre.svg","batch":"runtime-mining-flat-svg"},
    "goldShieldCore": {"name":"赤金护符盾核","icon100":"assets/item-icons/100/goldShieldCore.png","icon50":"assets/item-icons/50/goldShieldCore.png","batch":"p1-v4-no-outline"},
    "goldSwordBlank": {"name":"赤金飞剑胚","icon100":"assets/item-icons/100/goldSwordBlank.png","icon50":"assets/item-icons/50/goldSwordBlank.png","batch":"p1-v4-no-outline"},
    "imbuedPlate": {"name":"灵附甲片","icon100":"assets/item-icons/100/imbuedPlate.png","icon50":"assets/item-icons/50/imbuedPlate.png","batch":"p2-v4-no-outline"},
    "imbuedThread": {"name":"灵附丝线","icon100":"assets/item-icons/100/imbuedThread.png","icon50":"assets/item-icons/50/imbuedThread.png","batch":"p1-v4-no-outline"},
    "ironArmorPlate": {"name":"寒铁法甲片","icon100":"assets/item-icons/100/ironArmorPlate.png","icon50":"assets/item-icons/50/ironArmorPlate.png","batch":"p0-v4-no-outline"},
    "ironBar": {"name":"寒铁锭","icon100":"assets/item-icons/100/ironBar.png","icon50":"assets/item-icons/50/ironBar.png","batch":"p0-v4-no-outline"},
    "ironBootBlank": {"name":"寒铁踏云履胚","icon100":"assets/item-icons/100/ironBootBlank.png","icon50":"assets/item-icons/50/ironBootBlank.png","batch":"p0-v4-no-outline"},
    "ironBracerBlank": {"name":"寒铁护腕胚","icon100":"assets/item-icons/100/ironBracerBlank.png","icon50":"assets/item-icons/50/ironBracerBlank.png","batch":"p0-v4-no-outline"},
    "ironCrownBlank": {"name":"寒铁法冠胚","icon100":"assets/item-icons/100/ironCrownBlank.png","icon50":"assets/item-icons/50/ironCrownBlank.png","batch":"p0-v4-no-outline"},
    "ironDaggerBlank": {"name":"寒铁短刃胚","icon100":"assets/item-icons/100/ironDaggerBlank.png","icon50":"assets/item-icons/50/ironDaggerBlank.png","batch":"p0-v4-no-outline"},
    "ironHeavyBladeBlank": {"name":"寒铁重剑胚","icon100":"assets/item-icons/100/ironHeavyBladeBlank.png","icon50":"assets/item-icons/50/ironHeavyBladeBlank.png","batch":"p0-v4-no-outline"},
    "ironOre": {"name":"铁矿石","icon100":"assets/item-icons/100/ironOre.svg","icon50":"assets/item-icons/50/ironOre.svg","batch":"runtime-mining-flat-svg"},
    "ironShieldCore": {"name":"寒铁护符盾核","icon100":"assets/item-icons/100/ironShieldCore.png","icon50":"assets/item-icons/50/ironShieldCore.png","batch":"p0-v4-no-outline"},
    "ironSwordBlank": {"name":"寒铁飞剑胚","icon100":"assets/item-icons/100/ironSwordBlank.png","icon50":"assets/item-icons/50/ironSwordBlank.png","batch":"p0-v4-no-outline"},
    "jadeArmorPlate": {"name":"灵玉法甲片","icon100":"assets/item-icons/100/jadeArmorPlate.png","icon50":"assets/item-icons/50/jadeArmorPlate.png","batch":"p1-v4-no-outline"},
    "jadeBar": {"name":"灵玉锭","icon100":"assets/item-icons/100/jadeBar.png","icon50":"assets/item-icons/50/jadeBar.png","batch":"p1-v4-no-outline"},
    "jadeBootBlank": {"name":"灵玉踏云履胚","icon100":"assets/item-icons/100/jadeBootBlank.png","icon50":"assets/item-icons/50/jadeBootBlank.png","batch":"p1-v4-no-outline"},
    "jadeBracerBlank": {"name":"灵玉护腕胚","icon100":"assets/item-icons/100/jadeBracerBlank.png","icon50":"assets/item-icons/50/jadeBracerBlank.png","batch":"p1-v4-no-outline"},
    "jadeCrownBlank": {"name":"灵玉法冠胚","icon100":"assets/item-icons/100/jadeCrownBlank.png","icon50":"assets/item-icons/50/jadeCrownBlank.png","batch":"p1-v4-no-outline"},
    "jadeDaggerBlank": {"name":"灵玉短刃胚","icon100":"assets/item-icons/100/jadeDaggerBlank.png","icon50":"assets/item-icons/50/jadeDaggerBlank.png","batch":"p1-v4-no-outline"},
    "jadeHeavyBladeBlank": {"name":"灵玉重剑胚","icon100":"assets/item-icons/100/jadeHeavyBladeBlank.png","icon50":"assets/item-icons/50/jadeHeavyBladeBlank.png","batch":"p1-v4-no-outline"},
    "jadeShard": {"name":"灵玉矿","icon100":"assets/item-icons/100/jadeShard.svg","icon50":"assets/item-icons/50/jadeShard.svg","batch":"runtime-mining-flat-svg"},
    "jadeShieldCore": {"name":"灵玉护符盾核","icon100":"assets/item-icons/100/jadeShieldCore.png","icon50":"assets/item-icons/50/jadeShieldCore.png","batch":"p1-v4-no-outline"},
    "jadeSwordBlank": {"name":"灵玉飞剑胚","icon100":"assets/item-icons/100/jadeSwordBlank.png","icon50":"assets/item-icons/50/jadeSwordBlank.png","batch":"p1-v4-no-outline"},
    "lemontyleHerb": {"name":"柠光草","icon100":"assets/item-icons/100/lemontyleHerb.png","icon50":"assets/item-icons/50/lemontyleHerb.png","batch":"p1-v4-no-outline"},
    "lemontyleSeed": {"name":"柠光籽","icon100":"assets/item-icons/100/lemontyleSeed.png","icon50":"assets/item-icons/50/lemontyleSeed.png","batch":"p1-v4-no-outline"},
    "lingshi": {"name":"灵石","icon100":"assets/item-icons/100/lingshi.svg","icon50":"assets/item-icons/50/lingshi.svg","batch":"runtime-mining-flat-svg"},
    "mantalymeHerb": {"name":"曼塔草","icon100":"assets/item-icons/100/mantalymeHerb.png","icon50":"assets/item-icons/50/mantalymeHerb.png","batch":"p1-v4-no-outline"},
    "mantalymeSeed": {"name":"曼塔籽","icon100":"assets/item-icons/100/mantalymeSeed.png","icon50":"assets/item-icons/50/mantalymeSeed.png","batch":"p1-v4-no-outline"},
    "mithrilArmorPlate": {"name":"秘银法甲片","icon100":"assets/item-icons/100/mithrilArmorPlate.png","icon50":"assets/item-icons/50/mithrilArmorPlate.png","batch":"p1-v4-no-outline"},
    "mithrilBar": {"name":"秘银锭","icon100":"assets/item-icons/100/mithrilBar.png","icon50":"assets/item-icons/50/mithrilBar.png","batch":"p1-v4-no-outline"},
    "mithrilBootBlank": {"name":"秘银踏云履胚","icon100":"assets/item-icons/100/mithrilBootBlank.png","icon50":"assets/item-icons/50/mithrilBootBlank.png","batch":"p1-v4-no-outline"},
    "mithrilBracerBlank": {"name":"秘银护腕胚","icon100":"assets/item-icons/100/mithrilBracerBlank.png","icon50":"assets/item-icons/50/mithrilBracerBlank.png","batch":"p1-v4-no-outline"},
    "mithrilCrownBlank": {"name":"秘银法冠胚","icon100":"assets/item-icons/100/mithrilCrownBlank.png","icon50":"assets/item-icons/50/mithrilCrownBlank.png","batch":"p1-v4-no-outline"},
    "mithrilDaggerBlank": {"name":"秘银短刃胚","icon100":"assets/item-icons/100/mithrilDaggerBlank.png","icon50":"assets/item-icons/50/mithrilDaggerBlank.png","batch":"p1-v4-no-outline"},
    "mithrilHeavyBladeBlank": {"name":"秘银重剑胚","icon100":"assets/item-icons/100/mithrilHeavyBladeBlank.png","icon50":"assets/item-icons/50/mithrilHeavyBladeBlank.png","batch":"p1-v4-no-outline"},
    "mithrilOre": {"name":"秘银矿","icon100":"assets/item-icons/100/mithrilOre.svg","icon50":"assets/item-icons/50/mithrilOre.svg","batch":"runtime-mining-flat-svg"},
    "mithrilShieldCore": {"name":"秘银护符盾核","icon100":"assets/item-icons/100/mithrilShieldCore.png","icon50":"assets/item-icons/50/mithrilShieldCore.png","batch":"p1-v4-no-outline"},
    "mithrilSwordBlank": {"name":"秘银飞剑胚","icon100":"assets/item-icons/100/mithrilSwordBlank.png","icon50":"assets/item-icons/50/mithrilSwordBlank.png","batch":"p1-v4-no-outline"},
    "monsterCore": {"name":"妖核","icon100":"assets/item-icons/100/monsterCore.png","icon50":"assets/item-icons/50/monsterCore.png","batch":"p1-v4-no-outline"},
    "onyx": {"name":"缟玛瑙","icon100":"assets/item-icons/100/onyx.png","icon50":"assets/item-icons/50/onyx.png","batch":"p2-v4-no-outline"},
    "oxilymeHerb": {"name":"清氧草","icon100":"assets/item-icons/100/oxilymeHerb.png","icon50":"assets/item-icons/50/oxilymeHerb.png","batch":"p1-v4-no-outline"},
    "oxilymeSeed": {"name":"清氧籽","icon100":"assets/item-icons/100/oxilymeSeed.png","icon50":"assets/item-icons/50/oxilymeSeed.png","batch":"p1-v4-no-outline"},
    "pigtayleHerb": {"name":"赤尾草","icon100":"assets/item-icons/100/pigtayleHerb.png","icon50":"assets/item-icons/50/pigtayleHerb.png","batch":"p2-v4-no-outline"},
    "pigtayleSeed": {"name":"赤尾籽","icon100":"assets/item-icons/100/pigtayleSeed.png","icon50":"assets/item-icons/50/pigtayleSeed.png","batch":"p2-v4-no-outline"},
    "poraxxHerb": {"name":"紫魄草","icon100":"assets/item-icons/100/poraxxHerb.png","icon50":"assets/item-icons/50/poraxxHerb.png","batch":"p2-v4-no-outline"},
    "poraxxSeed": {"name":"紫魄籽","icon100":"assets/item-icons/100/poraxxSeed.png","icon50":"assets/item-icons/50/poraxxSeed.png","batch":"p2-v4-no-outline"},
    "pureSpiritEssence": {"name":"纯灵精粹","icon100":"assets/item-icons/100/pureSpiritEssence.png","icon50":"assets/item-icons/50/pureSpiritEssence.png","batch":"p2-v4-no-outline"},
    "ruby": {"name":"红宝","icon100":"assets/item-icons/100/ruby.svg","icon50":"assets/item-icons/50/ruby.svg","batch":"runtime-mining-flat-svg"},
    "runeBar": {"name":"符纹锭","icon100":"assets/item-icons/100/runeBar.png","icon50":"assets/item-icons/50/runeBar.png","batch":"p2-v4-no-outline"},
    "runecraftingPouch": {"name":"符纹包","icon100":"assets/item-icons/100/runecraftingPouch.png","icon50":"assets/item-icons/50/runecraftingPouch.png","batch":"p1-v4-no-outline"},
    "runeOre": {"name":"符纹矿","icon100":"assets/item-icons/100/runeOre.png","icon50":"assets/item-icons/50/runeOre.png","batch":"p2-v4-no-outline"},
    "sapphire": {"name":"蓝宝","icon100":"assets/item-icons/100/sapphire.svg","icon50":"assets/item-icons/50/sapphire.svg","batch":"runtime-mining-flat-svg"},
    "silverArmorPlate": {"name":"玄银法甲片","icon100":"assets/item-icons/100/silverArmorPlate.png","icon50":"assets/item-icons/50/silverArmorPlate.png","batch":"p1-v4-no-outline"},
    "silverBar": {"name":"玄银锭","icon100":"assets/item-icons/100/silverBar.png","icon50":"assets/item-icons/50/silverBar.png","batch":"p1-v4-no-outline"},
    "silverBootBlank": {"name":"玄银踏云履胚","icon100":"assets/item-icons/100/silverBootBlank.png","icon50":"assets/item-icons/50/silverBootBlank.png","batch":"p1-v4-no-outline"},
    "silverBracerBlank": {"name":"玄银护腕胚","icon100":"assets/item-icons/100/silverBracerBlank.png","icon50":"assets/item-icons/50/silverBracerBlank.png","batch":"p1-v4-no-outline"},
    "silverCrownBlank": {"name":"玄银法冠胚","icon100":"assets/item-icons/100/silverCrownBlank.png","icon50":"assets/item-icons/50/silverCrownBlank.png","batch":"p1-v4-no-outline"},
    "silverDaggerBlank": {"name":"玄银短刃胚","icon100":"assets/item-icons/100/silverDaggerBlank.png","icon50":"assets/item-icons/50/silverDaggerBlank.png","batch":"p1-v4-no-outline"},
    "silverHeavyBladeBlank": {"name":"玄银重剑胚","icon100":"assets/item-icons/100/silverHeavyBladeBlank.png","icon50":"assets/item-icons/50/silverHeavyBladeBlank.png","batch":"p1-v4-no-outline"},
    "silverOre": {"name":"银矿石","icon100":"assets/item-icons/100/silverOre.svg","icon50":"assets/item-icons/50/silverOre.svg","batch":"runtime-mining-flat-svg"},
    "silverShieldCore": {"name":"玄银护符盾核","icon100":"assets/item-icons/100/silverShieldCore.png","icon50":"assets/item-icons/50/silverShieldCore.png","batch":"p1-v4-no-outline"},
    "silverSwordBlank": {"name":"玄银飞剑胚","icon100":"assets/item-icons/100/silverSwordBlank.png","icon50":"assets/item-icons/50/silverSwordBlank.png","batch":"p1-v4-no-outline"},
    "soulShard": {"name":"魂晶碎片","icon100":"assets/item-icons/100/soulShard.png","icon50":"assets/item-icons/50/soulShard.png","batch":"p2-v4-no-outline"},
    "soulUrn": {"name":"魂瓮","icon100":"assets/item-icons/100/soulUrn.png","icon50":"assets/item-icons/50/soulUrn.png","batch":"p2-v4-no-outline"},
    "sourweedHerb": {"name":"酸藤草","icon100":"assets/item-icons/100/sourweedHerb.png","icon50":"assets/item-icons/50/sourweedHerb.png","batch":"p0-v4-no-outline"},
    "sourweedSeed": {"name":"酸藤种子","icon100":"assets/item-icons/100/sourweedSeed.png","icon50":"assets/item-icons/50/sourweedSeed.png","batch":"p0-v4-no-outline"},
    "spiritAzureJadePendant": {"name":"灵青空玉坠","icon100":"assets/item-icons/100/spiritAzureJadePendant.png","icon50":"assets/item-icons/50/spiritAzureJadePendant.png","batch":"p2-v4-no-outline"},
    "spiritAzureJadeRing": {"name":"灵青空玉戒","icon100":"assets/item-icons/100/spiritAzureJadeRing.png","icon50":"assets/item-icons/50/spiritAzureJadeRing.png","batch":"p2-v4-no-outline"},
    "spiritClaw": {"name":"妖灵爪","icon100":"assets/item-icons/100/spiritClaw.png","icon50":"assets/item-icons/50/spiritClaw.png","batch":"p1-v4-no-outline"},
    "spiritDiamondPendant": {"name":"灵钻坠","icon100":"assets/item-icons/100/spiritDiamondPendant.png","icon50":"assets/item-icons/50/spiritDiamondPendant.png","batch":"p1-v4-no-outline"},
    "spiritDiamondRing": {"name":"灵钻戒","icon100":"assets/item-icons/100/spiritDiamondRing.png","icon50":"assets/item-icons/50/spiritDiamondRing.png","batch":"p1-v4-no-outline"},
    "spiritEmeraldPendant": {"name":"灵祖母绿坠","icon100":"assets/item-icons/100/spiritEmeraldPendant.png","icon50":"assets/item-icons/50/spiritEmeraldPendant.png","batch":"p1-v4-no-outline"},
    "spiritEmeraldRing": {"name":"灵祖母绿戒","icon100":"assets/item-icons/100/spiritEmeraldRing.png","icon50":"assets/item-icons/50/spiritEmeraldRing.png","batch":"p1-v4-no-outline"},
    "spiritEssence": {"name":"灵髓","icon100":"assets/item-icons/100/spiritEssence.png","icon50":"assets/item-icons/50/spiritEssence.png","batch":"p0-v4-no-outline"},
    "spiritOnyxPendant": {"name":"灵缟玛瑙坠","icon100":"assets/item-icons/100/spiritOnyxPendant.png","icon50":"assets/item-icons/50/spiritOnyxPendant.png","batch":"p2-v4-no-outline"},
    "spiritOnyxRing": {"name":"灵缟玛瑙戒","icon100":"assets/item-icons/100/spiritOnyxRing.png","icon50":"assets/item-icons/50/spiritOnyxRing.png","batch":"p2-v4-no-outline"},
    "spiritRubyPendant": {"name":"灵红玉坠","icon100":"assets/item-icons/100/spiritRubyPendant.png","icon50":"assets/item-icons/50/spiritRubyPendant.png","batch":"p1-v4-no-outline"},
    "spiritRubyRing": {"name":"灵红玉戒","icon100":"assets/item-icons/100/spiritRubyRing.png","icon50":"assets/item-icons/50/spiritRubyRing.png","batch":"p1-v4-no-outline"},
    "spiritSapphirePendant": {"name":"蓝玉法坠","icon100":"assets/item-icons/100/spiritSapphirePendant.png","icon50":"assets/item-icons/50/spiritSapphirePendant.png","batch":"p0-v4-no-outline"},
    "spiritSapphireRing": {"name":"蓝玉灵戒","icon100":"assets/item-icons/100/spiritSapphireRing.png","icon50":"assets/item-icons/50/spiritSapphireRing.png","batch":"p0-v4-no-outline"},
    "spiritScale": {"name":"妖灵鳞","icon100":"assets/item-icons/100/spiritScale.png","icon50":"assets/item-icons/50/spiritScale.png","batch":"p1-v4-no-outline"},
    "spiritTopazPendant": {"name":"黄玉法坠","icon100":"assets/item-icons/100/spiritTopazPendant.png","icon50":"assets/item-icons/50/spiritTopazPendant.png","batch":"p0-v4-no-outline"},
    "spiritTopazRing": {"name":"黄玉灵戒","icon100":"assets/item-icons/100/spiritTopazRing.png","icon50":"assets/item-icons/50/spiritTopazRing.png","batch":"p0-v4-no-outline"},
    "spiritUrn": {"name":"聚灵瓶","icon100":"assets/item-icons/100/spiritUrn.png","icon50":"assets/item-icons/50/spiritUrn.png","batch":"p0-v4-no-outline"},
    "spiritVoidheartGemPendant": {"name":"灵虚心石坠","icon100":"assets/item-icons/100/spiritVoidheartGemPendant.png","icon50":"assets/item-icons/50/spiritVoidheartGemPendant.png","batch":"p2-v4-no-outline"},
    "spiritVoidheartGemRing": {"name":"灵虚心石戒","icon100":"assets/item-icons/100/spiritVoidheartGemRing.png","icon50":"assets/item-icons/50/spiritVoidheartGemRing.png","batch":"p2-v4-no-outline"},
    "spiritWindCrystalPendant": {"name":"灵风晶坠","icon100":"assets/item-icons/100/spiritWindCrystalPendant.png","icon50":"assets/item-icons/50/spiritWindCrystalPendant.png","batch":"p2-v4-no-outline"},
    "spiritWindCrystalRing": {"name":"灵风晶戒","icon100":"assets/item-icons/100/spiritWindCrystalRing.png","icon50":"assets/item-icons/50/spiritWindCrystalRing.png","batch":"p2-v4-no-outline"},
    "steelArmorPlate": {"name":"精钢法甲片","icon100":"assets/item-icons/100/steelArmorPlate.png","icon50":"assets/item-icons/50/steelArmorPlate.png","batch":"p1-v4-no-outline"},
    "steelBar": {"name":"精钢锭","icon100":"assets/item-icons/100/steelBar.png","icon50":"assets/item-icons/50/steelBar.png","batch":"p1-v4-no-outline"},
    "steelBootBlank": {"name":"精钢踏云履胚","icon100":"assets/item-icons/100/steelBootBlank.png","icon50":"assets/item-icons/50/steelBootBlank.png","batch":"p1-v4-no-outline"},
    "steelBracerBlank": {"name":"精钢护腕胚","icon100":"assets/item-icons/100/steelBracerBlank.png","icon50":"assets/item-icons/50/steelBracerBlank.png","batch":"p1-v4-no-outline"},
    "steelCrownBlank": {"name":"精钢法冠胚","icon100":"assets/item-icons/100/steelCrownBlank.png","icon50":"assets/item-icons/50/steelCrownBlank.png","batch":"p1-v4-no-outline"},
    "steelDaggerBlank": {"name":"精钢短刃胚","icon100":"assets/item-icons/100/steelDaggerBlank.png","icon50":"assets/item-icons/50/steelDaggerBlank.png","batch":"p1-v4-no-outline"},
    "steelHeavyBladeBlank": {"name":"精钢重剑胚","icon100":"assets/item-icons/100/steelHeavyBladeBlank.png","icon50":"assets/item-icons/50/steelHeavyBladeBlank.png","batch":"p1-v4-no-outline"},
    "steelShieldCore": {"name":"精钢护符盾核","icon100":"assets/item-icons/100/steelShieldCore.png","icon50":"assets/item-icons/50/steelShieldCore.png","batch":"p1-v4-no-outline"},
    "steelSwordBlank": {"name":"精钢飞剑胚","icon100":"assets/item-icons/100/steelSwordBlank.png","icon50":"assets/item-icons/50/steelSwordBlank.png","batch":"p1-v4-no-outline"},
    "tinOre": {"name":"锡矿石","icon100":"assets/item-icons/100/tinOre.svg","icon50":"assets/item-icons/50/tinOre.svg","batch":"runtime-mining-flat-svg"},
    "topaz": {"name":"黄玉","icon100":"assets/item-icons/100/topaz.svg","icon50":"assets/item-icons/50/topaz.svg","batch":"runtime-mining-flat-svg"},
    "tribulationAsh": {"name":"劫灰","icon100":"assets/item-icons/100/tribulationAsh.png","icon50":"assets/item-icons/50/tribulationAsh.png","batch":"p2-v4-no-outline"},
    "voidBar": {"name":"虚空锭","icon100":"assets/item-icons/100/voidBar.png","icon50":"assets/item-icons/50/voidBar.png","batch":"p2-v4-no-outline"},
    "voidheartGem": {"name":"虚心石","icon100":"assets/item-icons/100/voidheartGem.png","icon50":"assets/item-icons/50/voidheartGem.png","batch":"p2-v4-no-outline"},
    "voidMarrow": {"name":"虚空髓","icon100":"assets/item-icons/100/voidMarrow.png","icon50":"assets/item-icons/50/voidMarrow.png","batch":"p2-v4-no-outline"},
    "voidOre": {"name":"虚空矿","icon100":"assets/item-icons/100/voidOre.png","icon50":"assets/item-icons/50/voidOre.png","batch":"p2-v4-no-outline"},
    "windCrystal": {"name":"风晶","icon100":"assets/item-icons/100/windCrystal.png","icon50":"assets/item-icons/50/windCrystal.png","batch":"p2-v4-no-outline"}
  };

  const FROZEN_ICONS = deepFreeze(ICONS);

  function get(itemId) {
    return FROZEN_ICONS[itemId] || null;
  }

  function list() {
    return Object.keys(FROZEN_ICONS).map(function (itemId) {
      const row = FROZEN_ICONS[itemId];
      return Object.freeze(Object.assign({ itemId: itemId }, row));
    });
  }

  return Object.freeze({
    ICONS: FROZEN_ICONS,
    get: get,
    list: list
  });
});
